cofe_app/urls.py
from django.urls import path
from .views import about_us, main, shopView, bookView, database, pay
app_name = 'cofe'

urlpatterns = [
    path('', main, name='main'),
    path('about_us/',  about_us, name='about_us'),
    path('shop/',  shopView, name='shop'),
    path('book/<int:pk>/',  bookView, name='book'),
    path('database/',  database, name='database'),
    path('pay<int:pk>/',  pay, name='pay')

]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('cofe_app.urls'))
]


from django.conf import settings
from django.conf.urls.static import static

urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cofe_app/models.py
from distutils.text_file import TextFile
from django.db import models
from django.forms import CharField, ImageField

# Create your models here.


class MainPage(models.Model):
    image = models.ImageField(upload_to='media/uploads')
    title = models.CharField(max_length=400)
    body  = models.TextField()
    about_us_product = models.CharField(max_length=200)
    video = models.FileField(upload_to='media/uploads')

class MainAboutProduct(models.Model):
    title = models.CharField(max_length=100)
    body = models.CharField(max_length=200)    


class Connection(models.Model):
	name = models.CharField(max_length=100)
	email = models.EmailField(max_length = 254)
	phone = models.IntegerField()
	special_request = models.TextField()
	created_at = models.DateTimeField(auto_now_add=True)

class About_us(models.Model):
    title = models.CharField(max_length=200)
    body = models.TextField()

class Mini_aboutUs(models.Model):
    body = models.TextField()    


class Products(models.Model):
    image = models.ImageField(upload_to='media/uploads')
    price = models.CharField(max_length=20)
    money = models.CharField(max_length=10)
    old_price = models.CharField(max_length=100, null=True, blank=True)
    about_product = models.TextField(null=True, blank=True)
    return_policy = models.TextField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)    

cofe_app/forms.py
from django.forms import ModelForm
from .models import Connection

class ConnectForm(ModelForm):
	class Meta:
		model = Connection
		fields = ('name', 'email', 'phone', 'special_request')

cofe_app/views.py
from django.shortcuts import render, redirect
from django.views import View
from .models import (MainPage, MainAboutProduct,
 Connection, About_us, Mini_aboutUs, Products)
from .forms import ConnectForm
# Create your views here.



def main(request):
    mainpage = MainPage.objects.all()
    aboutProduct = MainAboutProduct.objects.all()
    if request.POST:
    	name = request.POST['name']
    	email = request.POST['email']
    	phone = request.POST['phone']
    	requestt = request.POST['requestt']
    	Connection(name=name,phone=phone,email=email,special_request=requestt).save()
    	return redirect('cofe:main')
    
    return render(request, 'block_main.html', {'main':mainpage, 'aboutProduct': aboutProduct})


def about_us(request):
    about_us = About_us.objects.all()
    miniAboutus = Mini_aboutUs.objects.all()
    return render(request, 'about_us.html',{
        'about_us': about_us,
        'mini': miniAboutus
        })


def shopView(request):
    products = Products.objects.all()
    return render(request, 'shop.html',{'products':products})

def bookView(request, pk):
    product = Products.objects.get(id=pk)
    return render(request, 'book.html',{'product':product})    

def database(request):
	mainPage = MainPage.objects.all()
	aboutProduct = MainAboutProduct.objects.all()
	connection = Connection.objects.all()
	return render(request, 'database.html',{
		'main':mainPage,
		'aboutProduct': aboutProduct,
		'connection':connection
		})     

def pay(request, pk):
    quantity = request.POST['quantity']
    product = Products.objects.get(id=pk)
    return render(request, 'pay.html', {'quantity':quantity, 'product': product})    

templates/about_us.html
{% extends 'main.html' %}
{% load static %}
{% block content %}




<main>
    <section  id="about_us1">
        <div class="whoAreWe text-center">
            КТО МЫ<br>
            ТАКИЕ
        </div>
    </section>
    <section id="about_us2">
        <div class="container mt-5">
            <div class="row">
                {% for x in about_us %}
                <div class="col-6">
                    <div class="text-center mb-3"><img src="{% static 'image/icon.png' %}" alt=""></div>
                    <div class="text-center"><p>{{x.title}}</p></div>
                    <div class="text-center font-13 f-italic"> 
                        {{x.body}}</div>
                </div>
                {% endfor %}
                {% for x in mini %}
                <div class="col-4   mt-5">
                    <div class="text-center mb-3"><img src="{% static 'image/icon3.webp' %}" alt=""></div>
                    <div class="text-center m-auto font-13  f-italic" style="width: 70%;"> 
                        {{x.body}}</div>
                </div>
                {% endfor %}
                
            </div>
            <div class="text-center mt-5 mb-5">
                <button class="btn btn-primary rounded-0 px-3 m-auto">В МАГАЗИН ></button>
            </div>
        </div>
    </section>
</main>




{% endblock %}

templates/block_main.html
{% extends "main.html" %}
{% load static %}

{% block content %}

<main id="main" style="margin-top: 69px;">
    <section id="section1" >   
        <div>
            <img src="{% static 'image/person.webp' %}" alt="">
        </div>
        <div class="realy_voice">   
            НАСТОЯЩЕЕ
            ЗВУЧАНИЕ
            <br>        
             <button class="btn btn-primary px-5 rounded-0">Купит</button>
        </div>
    </section>
    <section id="section2">
        <div class="text-center f-italic d-flex align-items-center " style="height: 100vh;">
            <div>
                {% for x in main %}
                    <h6>{{x.title}}</h6>
                                <p style="    line-height: 1.5em;
                                text-align: center;
                                font-size: 13px;
                                width: 86%;
                            ">
                                {{x.body}}
                                </p> 
                {% endfor %}
               
            <button class="btn btn-primary px-3 rounded-0">В МАГАЗИН</button>
            </div>
            

        </div>
        <div>
            {% for x in main %}
                 <img src="{{x.image.url}}" alt="">
            {% endfor %}
           
        </div>
    </section>
    <section id="section3">
        {% for x in main %}
        <div class="about_us">
            <p>{{x.about_us_product}}</p>
        </div>

        <div class="text-center mt-5">
            <video width="700" height="300" autoplay controls>
                <source src="{{x.video}}" type="video/mp4">
            </video>
        </div>
        {% endfor %}
        <div class="bottom-image">
            <div class="row text-white" style="padding: 15px 120px;">
               {% for x in aboutProduct %}
                <div class="col-4 f-italic">
                    <h6 class="mt-5">
                        {{x.title}}
                    </h6>
                    
                    <p>
                       {{x.body}}
                    </p>

                </div>
                {% endfor %}
            </div>
        </div>


        
    </section>
    <section id="section4">
        <div class="about_us">
            <p>СВЯЗЬ</p>
        </div>

        <div id="input"  style="padding: 10px 310px;">
            <form action="{% url 'cofe:main' %}" method="post" class="d-flex">
                {% csrf_token %}
                <div>
                <input type="text" name="name" placeholder="Имя"> <br>
                <input type="email" name="email" placeholder="Эл.почта"><br>
                <input type="number" name="phone" placeholder="Телефон">
            </div>
            <div>
                <textarea name="requestt" placeholder="Добавьте сообшение..." id="" cols="30" rows="10"></textarea> <br>
                <input class="btn btn-primary rounded-0" type="submit" style="float: right;">Отправить</input>
                
            </div>
            </form>
           <div class="text-center mt-5">
            <p>Это заголовок. Кликните, чтобы отредактировать</p>

            <p class="font-13 f-italic">Это текст. Нажмите один раз и выберите «Редактировать текст» 
                или просто кликните дважды, чтобы добавить свой текст и настроить шрифт. Расскажите посетителям сайта о себе.</p>


                <p>Телефон: +7 (495) 000-00-00  /   Email: info@mysite.ru</p>

                <a href="#" >Узнать о нас больше > </a href="#"> <br>
                <button class="btn btn-primary mt-3 rounded-0 px-4">В МАГАЗИН ></button>
           </div>
        </div>
    </section>
   
</main>





<main>
    <section style="margin-top: 69px;">
        <div class="row">
            <div class="col-7">
                <h5>Моя корзина</h5>
            </div>
            <div class="col-5">
                <h5>Детали заказа</h5>
            </div>
        </div>
    </section>
</main>



{% endblock %}

templates/book.html
{% extends 'main.html' %}
{% load static %}

{% block content %}


<main>
    <section id="to_book1">
        <div class="container">
            <div class="row">
                <div class="col-7">
                   <div class="mb-4">
                    <a class="text-decoration-none text-dark" href="{% url 'cofe:main' %}">Home/ </a>
                    <a class="text-decoration-none text-dark" href="{% url 'cofe:shop' %}">Магазин/</a>
                    <a class="text-decoration-none text-dark" href="#">Ваш товар</a>
                    
                   </div>
                   
                       <div style="
                        border: 1px solid grey;
                        text-align: center;">
                           <img src="{{product.image.url}}" class="w-100" alt="">
                       </div>

                       <div>
                           <img src="{{product.image.url}}" style="width: 20px" alt="">
                          
                       </div>

                       <div class="font-13 mt-3">
                        Это описание товара. Здесь вы можете рассказать о
                         товаре подробнее: напишите о размерах, материалах, уходе и любых других важных моментах.
                       </div>

                   
                </div>
                <div class="col-5">
                    <div class="mt-5">
                        <h5>Ваш товар</h5>
                        
                        <p style="font-family: 'Franklin Gothic Medium', 'Arial Narrow', Arial, sans-serif;">{{product.money}}{{product.price}} </p>
                        <p class="mb-2" >Quantity</p>
                        <form method="post" action="{% url 'cofe:pay' product.id %}">
                            {% csrf_token %}
                            <input type="number" name="quantity" value="1" style="    width: 90px;
                            padding-left: 10px;
                            border: 1px solid grey;
                            height: 31px;"><br>
                            <input type="submit" class="btn btn-primary mt-3 w-100 rounded-0">Add to Cart</input>
                        </form>
                        
                    </div>
                    <div class="mt-4">
                        <p>О ТОВАРЕ</p>
                        <p class="font-13 f-italic">
                            {{product.about_product}}</p>
                    </div>
                    <hr>

                    <div>
                        <p>ПОЛИТИКА ВОЗВРАТА</p>
                        <p class="font-13 f-italic">
                            {{product.return_policy}}</p>
                    </div>

                        
                </div>
            </div>
        </div>
    </section>
</main>

<script type="text/javascript">
    const price = '',
    
</script>

{% endblock %}

templates/database.html
<!DOCTYPE html>
<html>
<head>
	 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    
	<title></title>
</head>
<body>

<div class="container">
	<div class="row">
		<div class="col-4">
			<div class="card">
				{% for x in main %}
				
					<div>
						<p>{{x.title}}</p>
						<p>{{x.body}}</p>
						<p>{{x.about_us_product}}</p>
						<p>{{x.video}}</p>
						<p>{{x.image.url}}</p>
					</div>

				{% endfor %}
			</div>
			
		</div>	

		<div class="col-4">
			<div class="card">
			{% for x in aboutProduct %}
				
				<div>
					<p>{{x.title}}</p>
					<p>{{x.body}}</p>
				</div>

			{% endfor %}</div>
		</div>	

		<div class="col-4">
			<div class="card">
				{% for x in connection %}
				
				<div>
					<p>{{x.name}}</p>
					<p>{{x.email}}</p>
					<p>{{x.phone}}</p>
					<p>{{x.special_request}}</p>
					<p>{{x.created_at}}</p>
		
				</div>

			{% endfor %}
			</div>
						
			
		</div>	
	</div>
</div>







</body>
</html>

templates/main.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/about_us.css' %}">
    <title>Shop</title>
</head>
<body>
    


<main>
    <section class="w-100 position-fixed top-0">
        <nav class="d-flex justify-content-between text-white bg-dark" style="padding: 13px 130px;">
            <h3 class="text-primary">МЕГАБИТ</h3>
            <div class="d-flex align-items-center">
                <h5 class="ms-4 mb-0"><a class="text-decoration-none text-white" href="{% url 'cofe:main' %}">ГЛАВНАЯ</a></h5>
                <h5 class="ms-4 mb-0"> <a class="text-decoration-none text-white" href="{% url 'cofe:about_us' %}">О НАС</a> </h5>
                <h5 class="ms-4 mb-0"> <a class="text-decoration-none text-white" href="{% url 'cofe:shop' %}">МАГАЗИН</a> </h5>
            </div>
        </nav>
    </section>
    {% block content %}

    {% endblock %}

    <section id="section5" class="mt-5">
        <p class="font-13">
            Узнать о нас больше >
            В МАГАЗИН >
            
            © 2023 МЕГАБИТ. Сайт создан на Wix.com</p>
    </section>
</main>


</body>
</html>

templates/pay.html
{% extends 'main.html' %}
{% load static %}
{% block content %}



<main>
    <section id="pay" class="mb-5" style="margin-top: 269px;">
        <div class="container">
            <div class="row">
                <div class="col-8" >
                    <h4>Моя корзина</h4>
                    <hr style="width: 90%">
                    <div class="d-flex mt-5 mb-5">
                        <div style="    width: 136px; border: 1px solid grey;">
                            <img style="width: 130px;" src="{{product.image.url}}">
                        </div>

                        <div class="ms-3" style="margin-right: 170px">
                            <h6>Ваш товар</h6>
                            <p id="price">{{product.money}}{{product.price}}</p>
                        </div>

                        <div class="quantity">
                            <button onclick="minus()"  class="mb-0">-</button>
                            <p id="count" class="mb-0">{{quantity}}</p>
                            <button onclick="add()" class="mb-0">+</button>
                        </div>
                        <div class="ms-5">
                            <p class="mb-0 mt-1" id="all_price">{{product.money}}{{product.price}}</p>
                        </div>
                    </div>
                    <hr style="width: 90%">
                </div>
                
                <div class="col-4">
                    <h4>Детали заказа</h4>
                    <hr>
                    <div class="d-flex justify-content-between mt-5 mb-5">
                        <div>
                            <h5 style="font-weight: 100" class="mb-0">Сумма</h5>
                        </div>
                        <div>
                            <h5 style="font-weight: 100" class="mb-0 mt-1" id="all_price">{{product.money}}{{product.price}}</h5>
                        </div>
                    </div>
                    <hr>
                    <div class="d-flex  justify-content-between">
                        <div>
                            <h5 style="font-weight: 100" class="mb-0">Итого</h5>
                        </div>
                        <div>
                            <h5 style="font-weight: 100" class="mb-0 mt-1" id="all_price">{{product.money}}{{product.price}}</h5>
                        </div>
                    </div>
                    <button class="w-100 btn btn-primary text-center rounded-0 mt-4 py-3">Оформить заказ</button>
                    <div class="text-center">
                        Безопасный платеж
                    </div>
                </div>
                
            </div>
        </div>
        
    </section>
</main>
    
<script type="text/javascript">
    let count =  parseInt(document.getElementById("count").innerHTML)
    function add() {
        count += 1;
        s = document.getElementById("count").innerHTML = count;
        price = document.getElementById("price").innerHTML;
        a = s * price[3];
        document.getElementById("all_price").innerHTML = a;
    }
    function minus() {
        count -= 1;
        s = document.getElementById("count").innerHTML = count;
        price = document.getElementById("price").innerHTML;
        a = s * price[3];
        document.getElementById("all_price").innerHTML = a;
        // location.reload()
    }

        
    


</script>

{% endblock %}

templates/shop.html
{% extends 'main.html' %}
{% load static %}
{% block content %}





<main>
    <section id="about_us1" class="mb-5">
        <div class="whoAreWe text-center">
            НАШИ <br>
             НАУШНИКИ
        </div>

        <div class="shopping container" style="padding: 20px 70px">
            <div class="row">
                {% for x in products %}
                <div class="col-3">
                    <div>
                        <a href="{% url 'cofe:book' x.id %}"><img style="width: 70%;" src="{{x.image.url}}" alt=""></a>
                    </div>
                    <div>
                        <p style="font-size: 12px;" class="mb-1">Ваш товар</p>
                        <p style="font-size: 12px;" class="mb-1">
                            {% if x.old_price %}
                            <del>{{x.old_price}}</del>
                            {% endif %}
                        {{x.money}}{{x.price}}</p>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </section>
</main>





{% endblock %}